name: netsuite_connector
description: A module which makes connecting to Netsuite RESTlets using OAuth much easier.
version: 1.0.2
homepage: https://github.com/pravinkumarravi/netsuite_connector
license: Apache-2.0
author: pravinkumarravi <pravinkumar.ravi@gmail.com>
url: https://github.com/pravinkumarravi/netsuite-connector

environment:
  sdk: ">=2.18.2 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

dependencies:
  crypto: ^3.0.2
  http: ^0.13.5
